### ISSUE TITLE
Full upgrade 

### ISSUE THREAD

**Issue by ric96** [Hexxeh/rpi-update#155]
Maybe add apt-get upgrade to make RPI-update a complete raspberry pi updater.

**Comment by edoz90** [comment]
I'm using an alias to update firmware and debian pkgs:
alias update='sudo apt-get update && sudo apt-get dist-upgrade && sudo rpi-update'

**Comment by popcornmix** [comment]
I don't think rpi-update should use apt-get itself.
Creating an alias or a script is the right option.

Note: rpi-update shouldn't be part of the default update instructions.
rpi-update gives you test firmware. Useful if you want to help with testing, or you need a fix for a newly resolved bug, but otherwise the apt-get firmware is recommended.
